version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:23.4'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/configs/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/configs/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9012:9012'
      - '127.0.0.1:9009:9009'
    depends_on:
      - ch-zookeeper

  ch-zookeeper:
    image: zookeeper:3.7
    container_name: ch-zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=ch-zookeeper:2888:3888
    ports:
      - "9181:9181"
    restart: always
networks:
  default:
    driver: bridge
