
version: '1'  # Указывает версию файла конфигурации Docker Compose. Здесь используется версия 1.

services:  # Начало секции, где определяются сервисы, которые будут запущены в контейнерах.

  app:  # Определение сервиса с именем 'app'.
    build:  # Указывает, что нужно создать образ для сервиса.
      context: ./app  # Указывает путь к директории, где находятся файлы для сборки образа.

    ports:  # Настройка портов для данного сервиса.
      - "3001:3000"  # Прокидывает порт 3000 контейнера на порт 3001 хоста.

  my:  # Определение другого сервиса с именем 'my'.
    build:  # Указывает, что нужно создать образ для этого сервиса.
      context: ./my  # Указывает путь к директории, где находятся файлы для сборки образа.

    volumes:  # Настройка томов для данного сервиса.
      - ./my/index.js:/app/index.js  # Монтирует файл index.js из директории 'my' на хосте в контейнер по пути /app/index.js.

    ports:  # Настройка портов для данного сервиса.
      - "3002:3000"  # Прокидывает порт 3000 контейнера на порт 3002 хоста.

